services:
  portfolio:
    image: ghcr.io/maelaubert56/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
